default_platform(:android)

platform :android do
  desc "Run Flutter tests"
  lane :test do
    sh("cd .. && flutter test")
  end

  desc "Build Android App Bundle (.aab) for release"
  lane :build_release do
    sh("cd .. && flutter pub get")
    sh("cd .. && flutter build appbundle --release")
  end

  desc "Build Android APK for release"
  lane :build_apk do
    sh("cd .. && flutter pub get")
    sh("cd .. && flutter build apk --release")
  end

  desc "Deploy Android release to Play internal testing track"
  lane :internal do
    build_release
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Deploy Android release to Play production track"
  lane :deploy do
    build_release
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
